<div class="jumbotron">
    <h1>Sobre o projeto</h1>
    <p class="lead">
        Esse projeto consiste em uma simples Agenda de Contatos feita em 
        Zend Framework 2.
    </p>
    
    <h3>Ferramentas utilizadas:</h3>
    
    <ul class="list-inline">
        <li> <span class="label label-primary">Ubuntu 13.10</span></li>
        <li> <span class="label label-primary">Zend Server</span></li>
        <li> <span class="label label-primary">Zend Framework 2</span></li>
        <li> <span class="label label-primary">ZFTool</span></li>
        <li> <span class="label label-primary">Composer</span></li>
        <li> <span class="label label-primary">Apache</span></li>
        <li> <span class="label label-primary">VHOST</span></li>
        <li> <span class="label label-primary">Php 5.5</span></li>
        <li> <span class="label label-primary">Servidor interno Php 5.5</span></li>
        <li> <span class="label label-primary">Netbeans 8.0</span></li>
        <li> <span class="label label-primary">Github</span></li>
        <li> <span class="label label-primary">Bootstrap</span></li>
        <li> <span class="label label-primary">JQuery</span></li>
        <li> <span class="label label-primary">Mysql</span></li>
    </ul>
    </ul>
</div>